# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-16 15:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desafio', '0002_remove_desafio_contexto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='desafio',
            name='actualizado_el',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='desafio',
            name='creado_el',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
