# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-30 16:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('desafio', '0004_documento'),
    ]

    operations = [
        migrations.RenameField(
            model_name='documento',
            old_name='upload',
            new_name='documento',
        ),
    ]
