# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-09 15:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0002_auto_20150616_2121'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ciudad', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Convocatoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=250)),
                ('descripcion', models.TextField()),
                ('lugar', models.CharField(max_length=250)),
                ('fecha_desde', models.DateField()),
                ('fecha_hasta', models.DateField()),
                ('publicada', models.BooleanField(default=False)),
                ('creada_el', models.DateTimeField()),
                ('actualizada_el', models.DateTimeField()),
                ('ciudad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='convocatoria.Ciudad')),
                ('tematicas', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
        ),
    ]
