# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-09 15:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('convocatoria', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='convocatoria',
            name='actualizada_el',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='convocatoria',
            name='ciudad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='convocatoria.Ciudad'),
        ),
        migrations.AlterField(
            model_name='convocatoria',
            name='creada_el',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='convocatoria',
            name='fecha_desde',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='convocatoria',
            name='fecha_hasta',
            field=models.DateField(auto_now_add=True),
        ),
    ]
