# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-11 11:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convocatoria', '0002_auto_20170809_1519'),
    ]

    operations = [
        migrations.AddField(
            model_name='convocatoria',
            name='imagen',
            field=models.ImageField(default='images/no-img.png', upload_to='images/'),
        ),
    ]
