# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-06 12:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convocatoria', '0005_auto_20170822_1554'),
    ]

    operations = [
        migrations.AddField(
            model_name='convocatoria',
            name='premio',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='convocatoria',
            name='premio_descripcion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
