# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-15 16:17
from __future__ import unicode_literals

import convocatoria.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('convocatoria', '0006_auto_20171106_1228'),
    ]

    operations = [
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(blank=True, max_length=255)),
                ('upload', models.FileField(upload_to=convocatoria.models.convocatoria_directory_path)),
                ('subido_el', models.DateTimeField(auto_now_add=True)),
                ('convocatoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='convocatoria.Convocatoria')),
            ],
        ),
    ]
