# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-29 15:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('convocatoria', '0007_documento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documento',
            name='convocatoria',
        ),
        migrations.DeleteModel(
            name='Documento',
        ),
    ]
